/*
SISTEMA COMPLETO PARA FACTURACION DE MEDICAMENTOS
*/

-- USUARIOS : VENDEDOR, BODEGUERO, CLIENTE
--CREATE TABLE USUARIOS (

--);

CREATE SEQUENCE SEC_CIUDADES;

CREATE TABLE CIUDADES (
    ID_CIU NUMBER PRIMARY KEY,
    NOM_CIU VARCHAR(20) NOT NULL
);

INSERT INTO CIUDADES VALUES (SEC_CIUDADES.NEXTVAL,'AMBATO');
INSERT INTO CIUDADES VALUES (SEC_CIUDADES.NEXTVAL,'CUENCA');
INSERT INTO CIUDADES VALUES (SEC_CIUDADES.NEXTVAL,'GUAYAQUIL');
INSERT INTO CIUDADES VALUES (SEC_CIUDADES.NEXTVAL,'QUITO');

CREATE SEQUENCE SEC_CLIENTES;

CREATE TABLE CLIENTES (
    ID_CLI NUMBER PRIMARY KEY,
    CED_CLI VARCHAR(10) UNIQUE NOT NULL,
    NOM_CLI VARCHAR(15) NOT NULL,
    APE_CLI VARCHAR(15) NOT NULL,
    CIU_CLI REFERENCES CIUDADES (ID_CIU),
    DIR_CLI VARCHAR(50) NOT NULL,
    COR_CLI VARCHAR(50) NOT NULL,
	TEL_CLI VARCHAR(10) NOT NULL
);

INSERT INTO CLIENTES VALUES (SEC_CLIENTES.NEXTVAL,'1806542447','DANIELA','IPIALES',1,'MIRAFLORES','daniela@gmail.com','0991722125');
INSERT INTO CLIENTES VALUES (SEC_CLIENTES.NEXTVAL,'1804131100','PEDRO','JARAMILLO',1,'IZAMBA','pedro@gmail.com','0974088594');
INSERT INTO CLIENTES VALUES (SEC_CLIENTES.NEXTVAL,'1802477626','LUIS','CORDOVA',1,'MIRAFLORES','luis@gmail.com','0987376042');

CREATE SEQUENCE SEC_FARMACEUTICOS;

CREATE TABLE FARMACEUTICOS (
    ID_FAR NUMBER PRIMARY KEY,
    CED_FAR VARCHAR(10) UNIQUE NOT NULL,
    NOM_FAR VARCHAR(15) NOT NULL,
    APE_FAR VARCHAR(15) NOT NULL,
    COR_FAR VARCHAR(50) NOT NULL,
    TEL_FAR VARCHAR(10) NOT NULL,
    SUE_FAR FLOAT NOT NULL
);

INSERT INTO FARMACEUTICOS VALUES (SEC_FARMACEUTICOS.NEXTVAL,'1904290847','MONSERRATH','SALAZAR','monse@outlook.com','0985655446',500);
INSERT INTO FARMACEUTICOS VALUES (SEC_FARMACEUTICOS.NEXTVAL,'1906961085','BELEN','CAMACHO','belen@gmail.com','0985600389',700);

CREATE SEQUENCE SEC_BODEGUEROS;

CREATE TABLE BODEGUEROS (
    ID_BOD NUMBER PRIMARY KEY,
    CED_BOD VARCHAR(10) UNIQUE NOT NULL,
    NOM_BOD VARCHAR(15) NOT NULL,
    APE_BOD VARCHAR(15) NOT NULL,
    COR_BOD VARCHAR(50) NOT NULL,
    TEL_BOD VARCHAR(10) NOT NULL,
    SUE_BOD FLOAT NOT NULL
);

INSERT INTO BODEGUEROS VALUES (SEC_BODEGUEROS.NEXTVAL,'2005883368','MARCELA','VASQUEZ','marcela@outlook.com','0987341934',800);

CREATE SEQUENCE SEC_PROVEEDORES;

CREATE TABLE PROVEEDORES (
    ID_PRO NUMBER PRIMARY KEY,
    COD_PRO VARCHAR(5) UNIQUE NOT NULL,
    NOM_PRO VARCHAR(50) NOT NULL,
    CIU_PRO REFERENCES CIUDADES (ID_CIU),
    DIR_PRO VARCHAR(50) NOT NULL,
    COR_PRO VARCHAR(50) NOT NULL,
    TEL_PRO VARCHAR(10) NOT NULL
);

INSERT INTO PROVEEDORES VALUES (SEC_PROVEEDORES.NEXTVAL,'PRO01','CORPORACION APIX S.A',3,'AV LAS AMERICAS 510','atencion@apix.com','0994019636');
INSERT INTO PROVEEDORES VALUES (SEC_PROVEEDORES.NEXTVAL,'PRO02','TUCANHEALTH S.A',4,'AV PORTUGAL','serviciocliente@gmail.com','0991421788');

CREATE SEQUENCE SEC_MEDICAMENTOS;

CREATE TABLE MEDICAMENTOS(
    ID_MED NUMBER PRIMARY KEY,
    COD_MED VARCHAR(8) UNIQUE NOT NULL,
    NOM_MED VARCHAR(28) NOT NULL,
    MAR_MED VARCHAR(15) NOT NULL,
    FEC_EXP_MED DATE NOT NULL,
    MLG_MED INTEGER NOT NULL,
    PRES_MED VARCHAR(15) NOT NULL,
    PRE_COM_MED FLOAT NOT NULL,
    PRE_VEN_MED FLOAT NOT NULL,
    EXI_MED INTEGER NOT NULL,
    COD_PRO REFERENCES PROVEEDORES (COD_PRO)
);

INSERT INTO MEDICAMENTOS VALUES (SEC_MEDICAMENTOS.NEXTVAL,'M00E0001','SOLUCION DE AGUA DE MAR','MARIMER','01/03/2025',100,'SPRAY',13.57,14.14,9,'PRO02');
INSERT INTO MEDICAMENTOS VALUES (SEC_MEDICAMENTOS.NEXTVAL,'M00E0002','DESODORANTE ANT-MANCH-AMARI','DR DRY','27/12/2024',55,'ROLL ON',4.20,5.50,40,'PRO01');

CREATE TABLE VENTAS (
    NUM_FAC_VEN NUMBER PRIMARY KEY,
    FEC_FAC_VEN DATE  NOT NULL,
    CED_CLI_VEN REFERENCES CLIENTES (CED_CLI),
    CED_FAR_VEN REFERENCES FARMACEUTICOS (CED_FAR),
    TOT_VEN FLOAT NOT NULL,
    EST_VEN VARCHAR(1) NOT NULL
);

CREATE TABLE DETALLE_VENTA (
    COD_MED REFERENCES MEDICAMENTOS (COD_MED),
    CANT INTEGER NOT NULL,
    NUM_FAC_VEN REFERENCES VENTAS (NUM_FAC_VEN)
);

CREATE TABLE PEDIDOS (
    NUM_PED NUMBER PRIMARY KEY,
    FEC_HOR_PED DATE NOT NULL,
    CED_BOD_PED REFERENCES BODEGUEROS (CED_BOD),
    TOT_PED NUMBER NOT NULL,
    EST_PED VARCHAR(1) NOT NULL
);

CREATE TABLE DETALLE_PEDIDO (
    COD_MED REFERENCES MEDICAMENTOS (COD_MED),
    CANT INTEGER NOT NULL,
    NUM_PED REFERENCES PEDIDOS (NUM_PED)
);

/*
TABLAS CON RESPALDO:
                    - PEDIDOS
                    - DETALLE_PEDIDO
                    - VENTAS
                    - DETALLE_VENTA
*/

CREATE TABLE RESPALDO_PEDIDOS
AS
SELECT *
FROM PEDIDOS;

CREATE TABLE RESPALDO_DETALLE_PEDIDO
AS
SELECT *
FROM DETALLE_PEDIDO;

CREATE TABLE RESPALDO_VENTAS
AS
SELECT *
FROM VENTAS;

CREATE TABLE RESPALDO_DETALLE_VENTA
AS
SELECT *
FROM DETALLE_VENTA;

/*
TRIGGERS PARA RESPALDAR TABLAS
*/

---------------------------------------------
--RESPALDO_VENTAS
---------------------------------------------
CREATE OR REPLACE TRIGGER RESPALDO_VENTAS_INS
AFTER INSERT ON VENTAS
FOR EACH ROW
BEGIN
    INSERT INTO RESPALDO_VENTAS (NUM_FAC_VEN, FEC_FAC_VEN, CED_CLI_VEN, CED_FAR_VEN, TOT_VEN, EST_VEN)
    VALUES (:NEW.NUM_FAC_VEN,:NEW.FEC_FAC_VEN,:NEW.CED_CLI_VEN,:NEW.CED_FAR_VEN,:NEW.TOT_VEN,:NEW.EST_VEN);
END RESPALDO_VENTAS_INS;
.
/

CREATE OR REPLACE TRIGGER RESPALDO_VENTAS_DEL
AFTER DELETE ON VENTAS
FOR EACH ROW
BEGIN
    DELETE FROM RESPALDO_VENTAS
    WHERE NUM_FAC_VEN = :OLD.NUM_FAC_VEN;
END RESPALDO_VENTAS_DEL;
.
/
---------------------------------------------
--RESPALDO_DETALLE_VENTA
---------------------------------------------

CREATE OR REPLACE TRIGGER RESPALDO_DETALLE_VENTA_INS
AFTER INSERT ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    INSERT INTO RESPALDO_DETALLE_VENTA (COD_MED,CANT,NUM_FAC_VEN)
    VALUES (:NEW.COD_MED,:NEW.CANT,:NEW.NUM_FAC_VEN);
END RESPALDO_DETALLE_VENTA_INS;
.
/

CREATE OR REPLACE TRIGGER RESPALDO_DETALLE_VENTA_DEL
AFTER DELETE ON DETALLE_VENTA
FOR EACH ROW
BEGIN
    DELETE FROM RESPALDO_DETALLE_VENTA
    WHERE NUM_FAC_VEN = :OLD.NUM_FAC_VEN;
END RESPALDO_DETALLE_VENTA_DEL;
.
/

---------------------------------------------
--RESPALDO_PEDIDOS
---------------------------------------------
CREATE OR REPLACE TRIGGER RESPALDO_PEDIDOS_INS
AFTER INSERT ON PEDIDOS
FOR EACH ROW
BEGIN
    INSERT INTO RESPALDO_PEDIDOS (NUM_PED,FEC_HOR_PED,CED_BOD_PED,TOT_PED,EST_PED)
    VALUES (:NEW.NUM_PED,:NEW.FEC_HOR_PED,:NEW.CED_BOD_PED,:NEW.TOT_PED,:NEW.EST_PED);
END RESPALDO_PEDIDOS_INS;
.
/

CREATE OR REPLACE TRIGGER RESPALDO_PEDIDOS_DEL
AFTER DELETE ON PEDIDOS
FOR EACH ROW
BEGIN
    DELETE FROM RESPALDO_PEDIDOS
    WHERE NUM_PED = :OLD.NUM_PED;
END RESPALDO_PEDIDOS_DEL;
.
/

---------------------------------------------
--RESPALDO_DETALLE_PEDIDO
---------------------------------------------

CREATE OR REPLACE TRIGGER RESPALDO_DETALLE_PEDIDO_INS
AFTER INSERT ON DETALLE_PEDIDO
FOR EACH ROW
BEGIN
    INSERT INTO RESPALDO_DETALLE_PEDIDO (COD_MED,CANT,NUM_PED)
    VALUES (:NEW.COD_MED,:NEW.CANT,:NEW.NUM_PED);
END RESPALDO_DETALLE_PEDIDO_INS;
.
/

CREATE OR REPLACE TRIGGER RESPALDO_DETALLE_PEDIDO_DEL
AFTER DELETE ON DETALLE_PEDIDO
FOR EACH ROW
BEGIN
    DELETE FROM RESPALDO_DETALLE_PEDIDO
    WHERE NUM_PED = :OLD.NUM_PED;
END RESPALDO_DETALLE_PEDIDO_DEL;
.
/


---------------------------------------------
/*
TABLAS CON AUDITORIA COMPLETA:
                                - MEDICAMENTOS
*/

CREATE TABLE AUDITORIA_COM_MEDICAMENTOS (
    USUARIO VARCHAR(15),
    FECHA DATE,
    ACCION VARCHAR(15),
    COD_MED_OLD VARCHAR(8),
    COD_MED_NEW VARCHAR(8),
    NOM_MED_OLD VARCHAR(28),
    NOM_MED_NEW VARCHAR(28),
    MAR_MED_OLD VARCHAR(15),
    MAR_MED_NEW VARCHAR(15),
    FEC_EXP_MED_OLD DATE,
    FEC_EXP_MED_NEW DATE,
    MLG_MED_OLD INTEGER,
    MLG_MED_NEW INTEGER,
    PRES_MED_OLD VARCHAR(15),
    PRES_MED_NEW VARCHAR(15),
    PRE_COM_MED_OLD FLOAT,
    PRE_COM_MED_NEW FLOAT,
    PRE_VEN_MED_OLD FLOAT,
    PRE_VEN_MED_NEW FLOAT,
    EXI_MED_OLD INTEGER,
    EXI_MED_NEW INTEGER,
    COD_PRO_OLD REFERENCES PROVEEDORES (COD_PRO),
    COD_PRO_NEW REFERENCES PROVEEDORES (COD_PRO)
);

CREATE OR REPLACE TRIGGER AUDITORIA_COM_MEDICAMENTOS
AFTER INSERT OR UPDATE OR DELETE ON MEDICAMENTOS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO AUDITORIA_COM_MEDICAMENTOS (USUARIO,FECHA,ACCION,COD_MED_OLD,COD_MED_NEW,NOM_MED_OLD,NOM_MED_NEW,MAR_MED_OLD,MAR_MED_NEW,FEC_EXP_MED_OLD,FEC_EXP_MED_NEW,MLG_MED_OLD,MLG_MED_NEW,PRES_MED_OLD,PRES_MED_NEW,PRE_COM_MED_OLD,PRE_COM_MED_NEW,PRE_VEN_MED_OLD,PRE_VEN_MED_NEW,EXI_MED_OLD,EXI_MED_NEW,COD_PRO_OLD,COD_PRO_NEW)
        VALUES (USER,SYSDATE,'INSERTÓ',NULL,:NEW.COD_MED,NULL,:NEW.NOM_MED,NULL,:NEW.MAR_MED,NULL,:NEW.FEC_EXP_MED,NULL,:NEW.MLG_MED,NULL,:NEW.PRES_MED,NULL,:NEW.PRE_COM_MED,NULL,:NEW.PRE_VEN_MED,NULL,:NEW.EXI_MED,NULL,:NEW.COD_PRO);
    ELSE IF DELETING THEN
        INSERT INTO AUDITORIA_COM_MEDICAMENTOS (USUARIO,FECHA,ACCION,COD_MED_OLD,COD_MED_NEW,NOM_MED_OLD,NOM_MED_NEW,MAR_MED_OLD,MAR_MED_NEW,FEC_EXP_MED_OLD,FEC_EXP_MED_NEW,MLG_MED_OLD,MLG_MED_NEW,PRES_MED_OLD,PRES_MED_NEW,PRE_COM_MED_OLD,PRE_COM_MED_NEW,PRE_VEN_MED_OLD,PRE_VEN_MED_NEW,EXI_MED_OLD,EXI_MED_NEW,COD_PRO_OLD,COD_PRO_NEW)
        VALUES (USER,SYSDATE,'BORRÓ',:OLD.COD_MED,NULL,:OLD.NOM_MED,NULL,:OLD.MAR_MED,NULL,:OLD.FEC_EXP_MED,NULL,:OLD.MLG_MED,NULL,:OLD.PRES_MED,NULL,:OLD.PRE_COM_MED,NULL,:OLD.PRE_VEN_MED,NULL,:OLD.EXI_MED,NULL,:OLD.COD_PRO,NULL);
    ELSE IF UPDATING THEN
        INSERT INTO AUDITORIA_COM_MEDICAMENTOS (USUARIO,FECHA,ACCION,COD_MED_OLD,COD_MED_NEW,NOM_MED_OLD,NOM_MED_NEW,MAR_MED_OLD,MAR_MED_NEW,FEC_EXP_MED_OLD,FEC_EXP_MED_NEW,MLG_MED_OLD,MLG_MED_NEW,PRES_MED_OLD,PRES_MED_NEW,PRE_COM_MED_OLD,PRE_COM_MED_NEW,PRE_VEN_MED_OLD,PRE_VEN_MED_NEW,EXI_MED_OLD,EXI_MED_NEW,COD_PRO_OLD,COD_PRO_NEW)
        VALUES (USER,SYSDATE,'ACTUALIZÓ',:OLD.COD_MED,:NEW.COD_MED,:OLD.NOM_MED,:NEW.NOM_MED,:OLD.MAR_MED,:NEW.MAR_MED,:OLD.FEC_EXP_MED,:NEW.FEC_EXP_MED,:OLD.MLG_MED,:NEW.MLG_MED,:OLD.PRES_MED,:NEW.PRES_MED,:OLD.PRE_COM_MED,:NEW.PRE_COM_MED,:OLD.PRE_VEN_MED,:NEW.PRE_VEN_MED,:OLD.EXI_MED,:NEW.EXI_MED,:OLD.COD_PRO,:NEW.COD_PRO);
    END IF;
    END IF;
    END IF;
END;
.
/