CREATE TABLE PROVINCIAS (
    ID_PRO NUMBER PRIMARY KEY,
    COD_PRO VARCHAR(5) UNIQUE NOT NULL,
    NOM_PRO VARCHAR(35) NOT NULL
);

INSERT INTO PROVINCIAS  VALUES (1, 'GUAY', 'Guayas');
INSERT INTO PROVINCIAS  VALUES (2, 'PICH', 'Pichincha');
INSERT INTO PROVINCIAS  VALUES (3, 'AZUA', 'Azuay');
INSERT INTO PROVINCIAS  VALUES (4, 'SADO', 'Santo Domingo de los Tsáchilas');
INSERT INTO PROVINCIAS  VALUES (5, 'ELOR', 'El Oro');
INSERT INTO PROVINCIAS  VALUES (6, 'MANA', 'Manabí');
INSERT INTO PROVINCIAS  VALUES (7, 'LOJA', 'Loja');
INSERT INTO PROVINCIAS  VALUES (8, 'TUNG', 'Tungurahua');
INSERT INTO PROVINCIAS  VALUES (9, 'ESME', 'Esmeraldas');
INSERT INTO PROVINCIAS  VALUES (10, 'LOSR', 'Los Ríos');
INSERT INTO PROVINCIAS  VALUES (11, 'CHIM', 'Chimborazo');
INSERT INTO PROVINCIAS  VALUES (12, 'IMBA', 'Imbabura');
INSERT INTO PROVINCIAS  VALUES (13, 'SAEL', 'Santa Elena');
INSERT INTO PROVINCIAS  VALUES (14, 'COTO', 'Cotopaxi');
INSERT INTO PROVINCIAS  VALUES (15, 'CARC', 'Carchi');
INSERT INTO PROVINCIAS  VALUES (16, 'SUCU', 'Sucumbíos');
INSERT INTO PROVINCIAS  VALUES (17, 'OREL', 'Orellana');
INSERT INTO PROVINCIAS  VALUES (18, 'CAÑA', 'Cañar');
INSERT INTO PROVINCIAS  VALUES (19, 'PAST', 'Pastaza');
INSERT INTO PROVINCIAS  VALUES (20, 'BOLI', 'Bolívar');
INSERT INTO PROVINCIAS  VALUES (21, 'NAPO', 'Napo');
INSERT INTO PROVINCIAS  VALUES (22, 'MORO', 'Morona Santiago');
INSERT INTO PROVINCIAS  VALUES (23, 'ZAMO', 'Zamora Chinchipe');
INSERT INTO PROVINCIAS  VALUES (24, 'GALA', 'Galápagos');